server:
  port: 7002

eureka:
  instance:
    hostname: localhost  # Eureka服务端实例名
    instance-id: eureka-server-7002 # 自定义服务名称信息
    prefer-ip-address: true # 访问路径可以显示ip信息
  client:
#    registerWithEureka: false  # 实例是否在eureka服务器上注册自己的信息以供其他服务发现（默认为true）
#    fetchRegistry: false  # 此客户端是否获取eureka服务器注册表上的注册信息（默认为true,）
    serviceUrl:
      # 与Eureka注册服务中心的通信zone和url地址,用于查询服务和注册服务
      defaultZone: http://127.0.0.1:7001/eureka/
spring:
  application:
    name: eureka-server-7002